"""
app/utils/guardrails.py

Input and output guardrails for the RAG pipeline.

Responsibilities:
  - Reject questions unrelated to the loaded document.
  - Prevent hallucination by enforcing context-grounded answers.
  - Append a legal disclaimer.
  - Return a canned message when information is absent from the context.
"""

from __future__ import annotations

import re

from app.core.logging import log

# ── Constants ────────────────────────────────────────────────────────────────

LEGAL_DISCLAIMER = (
    "\n\n---\n*⚖️ Legal Disclaimer: This response is generated by an AI assistant "
    "for informational purposes only and does not constitute legal advice. "
    "Always consult a qualified legal professional for decisions based on "
    "contract content.*"
)

NOT_FOUND_RESPONSE = (
    "This information is not found in the document. "
    "Please upload the relevant contract and ask again."
)

# Patterns that suggest the question is off-topic / not about a document
_OFF_TOPIC_PATTERNS: list[re.Pattern[str]] = [
    re.compile(r"\b(weather|stock price|news|recipe|sport|movie|music|game)\b", re.I),
    re.compile(r"\b(who is|what is the capital|tell me a joke|write a poem)\b", re.I),
]

# Keywords that indicate a contract-related query
_CONTRACT_KEYWORDS: list[str] = [
    "contract", "clause", "party", "parties", "agreement", "obligation",
    "liability", "indemnif", "termination", "payment", "deliver", "breach",
    "penalty", "warranty", "govern", "jurisdict", "confidential", "intellectual",
    "property", "dispute", "arbitra", "force majeure", "amendment", "exhibit",
    "schedule", "effective date", "term", "condition", "signat",
]


def is_contract_related(question: str, context_available: bool) -> bool:
    """Determine if the question is plausibly related to a contract document.

    Args:
        question: The raw user question.
        context_available: True if a document has been loaded.

    Returns:
        True if the question should be answered, False if it should be rejected.
    """
    if not context_available:
        return False

    q_lower = question.lower()

    # Hard reject clearly off-topic patterns
    for pattern in _OFF_TOPIC_PATTERNS:
        if pattern.search(q_lower):
            log.warning("Guardrail: question rejected as off-topic: %r", question[:80])
            return False

    # Accept if it contains any contract-related keyword
    for kw in _CONTRACT_KEYWORDS:
        if kw in q_lower:
            return True

    # Accept short questions (pronouns like "it", "this") that reference prior context
    if len(question.split()) <= 8:
        return True

    log.warning(
        "Guardrail: question may be off-topic (no contract keywords): %r",
        question[:80],
    )
    return True  # Err on the side of answering; LLM will say "not found" if needed


def validate_answer(answer: str) -> str:
    """Post-process the LLM answer.

    - Detects suspiciously non-grounded phrases and replaces with NOT_FOUND.
    - Appends the legal disclaimer.

    Args:
        answer: Raw LLM response text.

    Returns:
        Validated and decorated answer string.
    """
    NOT_GROUNDED_PHRASES = [
        "i don't have access",
        "i cannot access",
        "i do not have information",
        "as an ai language model",
        "i'm unable to provide",
    ]
    lower = answer.lower()
    for phrase in NOT_GROUNDED_PHRASES:
        if phrase in lower:
            log.warning("Guardrail: LLM attempted non-grounded answer; replacing.")
            return NOT_FOUND_RESPONSE + LEGAL_DISCLAIMER

    return answer + LEGAL_DISCLAIMER


def guardrail_off_topic_response(question: str) -> str:
    """Return a standard rejection message for off-topic questions.

    Args:
        question: The rejected user question.

    Returns:
        A user-facing rejection string.
    """
    log.info("Returning off-topic rejection for: %r", question[:80])
    return (
        "⚠️ Your question does not appear to be related to the uploaded contract. "
        "Please ask questions about the content of the document you have uploaded."
        + LEGAL_DISCLAIMER
    )
